[package]
name = "tauri-plugin-bluetooth"
version = "0.1.1"
authors = ["ParticleG <particle_g@outlook.com>", "flaribbit <1149761294@qq.com>"]
edition = "2021"
rust-version = "1.77.2"
description = "Tauri plugin for Bluetooth Low Energy"
readme = "README.md"
repository = "https://github.com/26F-Studio/tauri-plugin-bluetooth"
license-file = "LICENSE"
links = "tauri-plugin-bluetooth"
exclude = [
    "/.github",
    "/examples",
    "/dist-js",
    "/guest-js",
    "/node_modules",
    "/.prettierrc.json",
    "/package.json",
    "/pnpm-lock.yaml",
    "/rollup.config.js",
    "/tsconfig.json",
]

[dependencies]
base64 = "0.22.1"
btleplug = { version = "0.11.7", features = ["serde"] }
log = "0.4.25"
serde = "1.0"
serde_json = "1.0"
tauri = { version = "2.2.4" }
thiserror = "2"
tokio = "1.43.0"
uuid = { version = "1.13.1", features = ["v4"] }

[target.'cfg(target_os = "android")'.dependencies]
jni = "0.19"

[build-dependencies]
tauri-plugin = { version = "2.0.3", features = ["build"] }
