[default]
description = "Default permissions for the plugin"
permissions = [
    "allow-ping",
    "allow-get-availability",
    "allow-request-device",
    "allow-scan-devices",
    "allow-start-continuous-scan",
    "allow-stop-continuous-scan",
    "allow-get-continuous-scan-results",
]
